/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ankita
 */
public class AddBook extends javax.swing.JFrame {

    /**de
     * Creates new form AddBook
     */
    public AddBook() {
        initComponents();
        setBookDetailsToTable();
    }
     public boolean checkDuplicateUser(){
        boolean isExist =false;
        try {
            Class.forName("com.mysql.jdbc.Driver");
                        Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");
                        String sql="select * from add_book1 where bookid='"+txtbookid.getText()+"'";
                        PreparedStatement pst= con.prepareStatement(sql);
                        ResultSet rs= pst.executeQuery();
                        if(rs.next()){
                            isExist = true;
                        }else{
                            isExist= false;
                        }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return isExist;
    }
    public void setBookDetailsToTable(){
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");
            String sql="select * from add_book1"; 
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            tblbookdetails1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ""+ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btndelette = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtbookid = new javax.swing.JTextField();
        txtbookname = new javax.swing.JTextField();
        txtrack = new javax.swing.JTextField();
        cmbedition = new javax.swing.JComboBox<>();
        txtprice = new javax.swing.JTextField();
        txtquantity = new javax.swing.JTextField();
        txtauthor = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbookdetails1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 260));
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btndelette.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndelette.setIcon(new javax.swing.ImageIcon("D:\\image\\Icon 1\\deleteicon1.jpg")); // NOI18N
        btndelette.setText("Delete");
        btndelette.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btndelette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelette, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 140, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 0));
        jLabel9.setText("Add Book");
        jLabel9.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 220, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 204));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Book_id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 140, 20));

        jLabel3.setBackground(new java.awt.Color(255, 255, 204));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Book Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 130, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 204));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rack");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 130, 20));

        jLabel5.setBackground(new java.awt.Color(255, 255, 204));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Eddition");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 140, 20));

        jLabel6.setBackground(new java.awt.Color(255, 255, 204));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 140, 20));

        jLabel7.setBackground(new java.awt.Color(255, 255, 204));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quantity");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 140, 20));

        jLabel8.setBackground(new java.awt.Color(255, 255, 204));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Author");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 120, 20));

        txtbookid.setBackground(new java.awt.Color(255, 255, 204));
        txtbookid.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        txtbookid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtbookidFocusLost(evt);
            }
        });
        txtbookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbookidActionPerformed(evt);
            }
        });
        jPanel1.add(txtbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 160, -1));

        txtbookname.setBackground(new java.awt.Color(255, 255, 204));
        txtbookname.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jPanel1.add(txtbookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 310, -1));

        txtrack.setBackground(new java.awt.Color(255, 255, 204));
        txtrack.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jPanel1.add(txtrack, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 310, -1));

        cmbedition.setBackground(new java.awt.Color(255, 255, 204));
        cmbedition.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        cmbedition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "1st", "2nd", "3rd", "4th", "5th", "6th" }));
        cmbedition.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbedition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbeditionActionPerformed(evt);
            }
        });
        jPanel1.add(cmbedition, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 310, -1));

        txtprice.setBackground(new java.awt.Color(255, 255, 204));
        txtprice.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jPanel1.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 310, -1));

        txtquantity.setBackground(new java.awt.Color(255, 255, 204));
        txtquantity.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jPanel1.add(txtquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 310, -1));

        txtauthor.setBackground(new java.awt.Color(255, 255, 204));
        txtauthor.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel1.add(txtauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 310, -1));

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon("D:\\image\\Icon 1\\save-icon--1.png")); // NOI18N
        btnsave.setText("Save");
        btnsave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 130, -1));

        btnclose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclose.setIcon(new javax.swing.ImageIcon("D:\\image\\clear2020.jpg")); // NOI18N
        btnclose.setText("Clear");
        btnclose.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 140, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\image\\background page.jpg")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1300, 450));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\image\\Icon 1\\red-x-mark-transparent-background-3.png")); // NOI18N
        jLabel11.setText("Close");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 80, 20));

        tblbookdetails1.setBackground(new java.awt.Color(204, 204, 204));
        tblbookdetails1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblbookdetails1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblbookdetails1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbookdetails1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbookdetails1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 520, 150));

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\image\\background page.jpg")); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 570, 450));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 550, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtbookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbookidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbookidActionPerformed

    private void cmbeditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbeditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbeditionActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        if((txtbookid.getText().equals(""))||txtbookname.getText().equals("")||txtauthor.getText().equals("")||cmbedition.getSelectedItem().equals("")||txtprice.getText().equals("")||txtquantity.equals("")||txtrack.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null,"Please fill Book Full Information!!!");
            }
            else
            {    
        try{
               Class.forName("com.mysql.jdbc.Driver");
                 Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");
                 String sql= "insert into add_book1(bookid,bookname,rack,authorname,edition,price,quantity)value('"+txtbookid.getText()+"','"+txtbookname.getText()+"','"+txtrack.getText()+"','"+txtauthor.getText()+"','"+cmbedition.getSelectedItem()+"','"+txtprice.getText()+"','"+txtquantity.getText()+"')";
                 PreparedStatement pst= con.prepareStatement(sql);
                 int i= pst.executeUpdate();
                 if(i>0)
                 {
                     JOptionPane.showMessageDialog(null, "Book Added!!!");
                     setVisible(false);
                     new  AddBook().setVisible(true);
                 } 
            }catch(Exception e){
// TODO add your handling code here:
                    JOptionPane.showMessageDialog(null, "Book id already exist!!!");
                     setVisible(false);
                     new  AddBook().setVisible(true);}
            }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        //setVisible(false);
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_btncloseActionPerformed

    private void tblbookdetails1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbookdetails1MouseClicked
        TableModel model = tblbookdetails1.getModel();
           int row = tblbookdetails1.getSelectedRow();
           
           txtbookid.setText(model.getValueAt(row, 0).toString());
           txtbookname.setText(model.getValueAt(row, 1).toString());
           txtrack.setText(model.getValueAt(row, 2).toString());
           txtauthor.setText(model.getValueAt(row, 3).toString());
           cmbedition.setSelectedItem(model.getValueAt(row, 4).toString());
           txtprice.setText(model.getValueAt(row, 5).toString());
           txtquantity.setText(model.getValueAt(row, 6).toString());
           //setVisible(true);
          // this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_tblbookdetails1MouseClicked

    private void btndeletteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletteActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Are you sure to Delete Record??");
                if(i==JOptionPane.YES_OPTION)
                {
                try{
                 Class.forName("com.mysql.jdbc.Driver");
                 Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");
                 String sql= "delete from  where add_book1 ";
                 PreparedStatement pst= con.prepareStatement(sql);
                 int j= pst.executeUpdate();
                 if(j>0)
                 {
                     JOptionPane.showMessageDialog(null, "Record Deleted");
                     
                 }
                }
                catch(Exception ex){
                     JOptionPane.showMessageDialog(null, ""+ex.getMessage());
                }
                }
                else
                if(i==JOptionPane.CANCEL_OPTION)
                {

                }
                else
               {
                   
               }
        // TODO add your handling code here:
    }//GEN-LAST:event_btndeletteActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void txtbookidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbookidFocusLost
        if(checkDuplicateUser()== true){
            JOptionPane.showMessageDialog(this, "Book Id already exist!!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbookidFocusLost
    public void clear(){
        txtbookid.setText("");
        txtauthor.setText("");
        txtbookname.setText("");txtprice.setText("");txtquantity.setText("");txtrack.setText("");cmbedition.setSelectedItem(null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndelette;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> cmbedition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblbookdetails1;
    private javax.swing.JTextField txtauthor;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JTextField txtbookname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtquantity;
    private javax.swing.JTextField txtrack;
    // End of variables declaration//GEN-END:variables
}
