/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagement;

/**
 *
 * @author Ankita
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        //setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnnewstudent = new javax.swing.JButton();
        btnaddbook = new javax.swing.JButton();
        btnissuebook = new javax.swing.JButton();
        btnreturnbook = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btnmenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnnewstudent.setBackground(new java.awt.Color(255, 255, 204));
        btnnewstudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnnewstudent.setIcon(new javax.swing.ImageIcon("D:\\image\\addstudent 5050.jpg")); // NOI18N
        btnnewstudent.setText("New Student");
        btnnewstudent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnnewstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewstudentActionPerformed(evt);
            }
        });
        jPanel1.add(btnnewstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, 50));

        btnaddbook.setBackground(new java.awt.Color(255, 255, 204));
        btnaddbook.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnaddbook.setIcon(new javax.swing.ImageIcon("D:\\image\\addimage5050.jpg")); // NOI18N
        btnaddbook.setText("Add Book");
        btnaddbook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnaddbook.setPreferredSize(new java.awt.Dimension(121, 27));
        btnaddbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddbookActionPerformed(evt);
            }
        });
        jPanel1.add(btnaddbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 150, 50));

        btnissuebook.setBackground(new java.awt.Color(255, 255, 204));
        btnissuebook.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnissuebook.setIcon(new javax.swing.ImageIcon("D:\\image\\Icon 1\\issue.png")); // NOI18N
        btnissuebook.setText("Issue Book");
        btnissuebook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnissuebook.setPreferredSize(new java.awt.Dimension(121, 27));
        btnissuebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnissuebookActionPerformed(evt);
            }
        });
        jPanel1.add(btnissuebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 180, 50));

        btnreturnbook.setBackground(new java.awt.Color(255, 255, 204));
        btnreturnbook.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnreturnbook.setIcon(new javax.swing.ImageIcon("D:\\image\\Icon 1\\return-book-1-560407.png")); // NOI18N
        btnreturnbook.setText("Return Book");
        btnreturnbook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnreturnbook.setPreferredSize(new java.awt.Dimension(121, 27));
        btnreturnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnbookActionPerformed(evt);
            }
        });
        jPanel1.add(btnreturnbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 190, 50));

        btnlogout.setBackground(new java.awt.Color(153, 204, 255));
        btnlogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlogout.setIcon(new javax.swing.ImageIcon("D:\\image\\Icon 1\\exit.png")); // NOI18N
        btnlogout.setText("Log Out");
        btnlogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlogout.setPreferredSize(new java.awt.Dimension(121, 27));
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 30, 140, 50));

        btnmenu.setBackground(new java.awt.Color(255, 255, 204));
        btnmenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnmenu.setIcon(new javax.swing.ImageIcon("D:\\image\\detail icon 5050.jpg")); // NOI18N
        btnmenu.setText("Details");
        btnmenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 150, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\image\\home2.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnnewstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewstudentActionPerformed
        new NewStudent().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnewstudentActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        setVisible(false);
        new StartProject().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnissuebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnissuebookActionPerformed
        new IssueBook().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnissuebookActionPerformed

    private void btnaddbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddbookActionPerformed
            new AddBook().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddbookActionPerformed

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        new PieChart().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmenuActionPerformed

    private void btnreturnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnbookActionPerformed
        new ReturnBook().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreturnbookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddbook;
    private javax.swing.JButton btnissuebook;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnnewstudent;
    private javax.swing.JButton btnreturnbook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
