/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Ankita
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form ReturnBook
     */
    public ReturnBook() {
        initComponents();
    }
    
    //to fetch the issue book details
    public void getIssueBookDetails(){
        //boolean success = false;
        try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");
                //String sql="select * from issuebook(id,name,bookname,issuedate,duedate)values('"+txtstudentid.getText()+"','"+txtstudentname.getText()+"','"+txtbookname.getText()+"','"+txtissuedate.getText()+"','"+txtduedate.getText()+"')";
                String sql="select * from issuebook where id = '"+txtid.getText()+"' and bookid = '"+txtbookid.getText()+"' and status = '1'";
                PreparedStatement pst=con.prepareStatement(sql);
                ResultSet rs=pst.executeQuery();
                if(rs.next()){
                    //success= true;
                    txtstudentid.setText(rs.getString("id"));
                    txtstudentname.setText(rs.getString("name"));
                    txtbookname.setText(rs.getString("bookname"));
                    txtissuedate.setText(rs.getString("issuedate"));
                    txtduedate.setText(rs.getString("duedate"));
                    //txtfine.setText("");
                }//else{
                     //txtfine.setText("No Record Found!!!");
//                    txtstudentid.setText("");
//                    txtstudentname.setText("");
//                    txtbookname.setText("");
//                    txtissuedate.setText("");
//                    txtduedate.setText("");
                    //success=false;
                //}
            }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, ""+e.getMessage()); 
        }
        //return success;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtduedate = new javax.swing.JTextField();
        txtissuedate = new javax.swing.JTextField();
        txtbookname = new javax.swing.JTextField();
        txtstudentname = new javax.swing.JTextField();
        txtstudentid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtbookid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtfine = new javax.swing.JTextField();
        txtreturndate1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnreturn = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        btnfind = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 260));
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Issued Book Details");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 250, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 204));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 120, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 204));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Book Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 204));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Issue Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 90, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 204));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Due Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 90, -1));

        txtduedate.setBackground(new java.awt.Color(255, 255, 204));
        txtduedate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtduedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 200, -1));

        txtissuedate.setBackground(new java.awt.Color(255, 255, 204));
        txtissuedate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtissuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 200, -1));

        txtbookname.setBackground(new java.awt.Color(255, 255, 204));
        txtbookname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtbookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 200, -1));

        txtstudentname.setBackground(new java.awt.Color(255, 255, 204));
        txtstudentname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtstudentname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 200, -1));

        txtstudentid.setBackground(new java.awt.Color(255, 255, 204));
        txtstudentid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtstudentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 200, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 204));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Student Id");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 100, -1));

        txtbookid.setBackground(new java.awt.Color(255, 255, 204));
        txtbookid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 220, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 204));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Book Id");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 100, -1));

        txtid.setBackground(new java.awt.Color(255, 255, 204));
        txtid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 220, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 204));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Return Date");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 100, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 204));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fine :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 90, -1));

        txtfine.setBackground(new java.awt.Color(255, 255, 204));
        txtfine.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtfine.setForeground(new java.awt.Color(204, 0, 0));
        txtfine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfineMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtfineMouseEntered(evt);
            }
        });
        jPanel1.add(txtfine, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 200, -1));

        txtreturndate1.setBackground(new java.awt.Color(255, 255, 204));
        txtreturndate1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtreturndate1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtreturndate1FocusGained(evt);
            }
        });
        txtreturndate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtreturndate1MouseClicked(evt);
            }
        });
        txtreturndate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreturndate1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtreturndate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 220, -1));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 0));
        jLabel13.setIcon(new javax.swing.ImageIcon("D:\\image\\Icon 1\\red-x-mark-transparent-background-3.png")); // NOI18N
        jLabel13.setText("Close");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 80, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Return Book");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 170, -1));

        btnreturn.setBackground(new java.awt.Color(255, 255, 204));
        btnreturn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnreturn.setIcon(new javax.swing.ImageIcon("D:\\image\\Icon 1\\return book png.png")); // NOI18N
        btnreturn.setText("Return");
        btnreturn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });
        jPanel1.add(btnreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 110, 30));

        btnclose.setBackground(new java.awt.Color(255, 255, 204));
        btnclose.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnclose.setIcon(new javax.swing.ImageIcon("D:\\image\\clear2020.jpg")); // NOI18N
        btnclose.setText("Clear");
        btnclose.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 90, 30));

        btnfind.setBackground(new java.awt.Color(255, 255, 204));
        btnfind.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnfind.setIcon(new javax.swing.ImageIcon("D:\\image\\details icon.jpg")); // NOI18N
        btnfind.setText("Find Details");
        btnfind.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnfind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnfindMouseClicked(evt);
            }
        });
        btnfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfindActionPerformed(evt);
            }
        });
        jPanel1.add(btnfind, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 150, 3));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 5, 320));

        jLabel2.setBackground(new java.awt.Color(255, 255, 204));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student Id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 240, 3));

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\image\\return baground.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
//        setVisible(false);
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfindActionPerformed
        getIssueBookDetails();
        //clear();
        //getIssueBookDetails();
// TODO add your handling code here:
    }//GEN-LAST:event_btnfindActionPerformed

    private void txtfineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfineMouseClicked
        try
        {   
           
        String dateBeforeString = txtduedate.getText();
        
        String dateAfterString =txtreturndate1.getText() ;
        
	LocalDate dateBefore = LocalDate.parse(dateBeforeString);
	LocalDate dateAfter = LocalDate.parse(dateAfterString);
		
	
	long noOfDaysBetween = ChronoUnit.DAYS.between(dateBefore, dateAfter);
        System.out.println(""+noOfDaysBetween);
		
	
        if(noOfDaysBetween>0)
        {
            double b1= (noOfDaysBetween*1);
	    double b2=((5*2)+(noOfDaysBetween-5)*3);
            double b3=((5*2)+(5*4)+(noOfDaysBetween-10)*5);
        

	if(noOfDaysBetween<=5)
        {
	
		txtfine.setText(""+b1);
        }
		
	else if(noOfDaysBetween>=6&&noOfDaysBetween<=10){
		
		
                txtfine.setText(""+b2);
	}
	else if(noOfDaysBetween>10&&noOfDaysBetween<=30){
		
		txtfine.setText(""+b3);
	}
	else if(noOfDaysBetween>30){
		
                JOptionPane.showMessageDialog(null,"your membership cancelled");
	}
	else{
		
                JOptionPane.showMessageDialog(null,"THANKS FOR BOOKS RETURN WITHIN TIME");
	}
        }
        else
        {
            //JOptionPane.showMessageDialog(null,"THANKS FOR BOOKS RETURN WITHIN TIME");
            txtfine.setText("0");
             
        }
        
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
        
    
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfineMouseClicked

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed
        if((txtbookid.getText().equals(""))||txtid.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null,"Please fill above complete details!!!");
            }
            else
            {
        String st="1";
        String st1="0";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");
            String sql="update issuebook set status='"+st1+"'where bookid='"+txtbookid.getText()+"'and id='"+txtid.getText()+"'and status='"+st+"'";
            PreparedStatement pst =con.prepareStatement(sql);
            int i=pst.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(null, "Book return successfully");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ""+ex.getMessage());
        }}clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreturnActionPerformed

    private void txtreturndate1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtreturndate1FocusGained
        try{
            Calendar calendar=Calendar.getInstance();
            //System.out.println("The current date is"+calendar.getTime());
            DateFormat formatter=new SimpleDateFormat("dd/MM/yyyy");
            //calendar.add(Calendar.DATE,+19);
            String dob=formatter.format(calendar.getTime());
            txtreturndate1.setText(dob);
            txtreturndate1.setEnabled(false);
            
            Date d1=null,d2=null;
            d1=formatter.parse(dob);
//            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ""+ex.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreturndate1FocusGained

    private void txtreturndate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreturndate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreturndate1ActionPerformed

    private void txtfineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfineMouseEntered
//        try
//    {   
//            Calendar calendar=Calendar.getInstance();
//            //System.out.println("The current date is"+calendar.getTime());
//            DateFormat formatter=new SimpleDateFormat("yyyy-MM-dd");
//            String dob=formatter.format(calendar.getTime());
//            txtreturndate.setText(dob);
//            txtreturndate.setEnabled(false);
//            
//            Date d1=null,d2=null;
//            d1=formatter.parse(dob);
//        String dateBeforeString = txtduedate.getText();
//        
//        String dateAfterString =txtreturndate.getText() ;
//        
//	LocalDate dateBefore = LocalDate.parse(dateBeforeString);
//	LocalDate dateAfter = LocalDate.parse(dateAfterString);
//		
//	
//	long noOfDaysBetween = ChronoUnit.DAYS.between(dateBefore, dateAfter);
//        System.out.println(""+noOfDaysBetween);
//		
//	
//        if(noOfDaysBetween>0)
//        {
//            double b1= (noOfDaysBetween*1);
//	    double b2=((5*2)+(noOfDaysBetween-5)*3);
//            double b3=((5*2)+(5*4)+(noOfDaysBetween-10)*5);
//        
//
//	if(noOfDaysBetween<=5)
//        {
//	
//		txtfine.setText(""+b1);
//        }
//		
//	else if(noOfDaysBetween>=6&&noOfDaysBetween<=10){
//		
//		
//                txtfine.setText(""+b2);
//	}
//	else if(noOfDaysBetween>10&&noOfDaysBetween<=30){
//		
//		txtfine.setText(""+b3);
//	}
//	else if(noOfDaysBetween>30){
//		
//                JOptionPane.showMessageDialog(null,"your membership cancelled");
//	}
//	else{
//		
//                JOptionPane.showMessageDialog(null,"THANKS FOR BOOKS RETURN WITHIN TIME");
//	}
//        }
//        else
//        {
//            //JOptionPane.showMessageDialog(null,"THANKS FOR BOOKS RETURN WITHIN TIME");
//            txtfine.setText("0");
//             
//        }
//        
//    }
//    catch(Exception e)
//    {
//        JOptionPane.showMessageDialog(null, e.getMessage());
   // }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfineMouseEntered

    private void txtreturndate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtreturndate1MouseClicked
        try
            
        {
        Calendar calendar=Calendar.getInstance();
            System.out.println("The current date is"+calendar.getTime());
            DateFormat formatter=new SimpleDateFormat("yyyy-MM-dd");
            String dob=formatter.format(calendar.getTime());
            txtreturndate1.setText(dob);
            txtreturndate1.setEnabled(false);
            
            Date d1=null,d2=null;
            d1=(Date)formatter.parse(dob);
        }
        catch(Exception e)
        {
            
        }
                 // TODO add your handling code here:
    }//GEN-LAST:event_txtreturndate1MouseClicked

    private void btnfindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfindMouseClicked
      
//       getIssueBookDetails();
//      clear();
    }//GEN-LAST:event_btnfindMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked
    public void clear(){
        txtbookid.setText("");txtbookname.setText("");txtduedate.setText("");txtfine.setText("");
        txtid.setText("");txtissuedate.setText("");txtreturndate1.setText("");txtstudentid.setText("");
        txtstudentname.setText("");
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnfind;
    private javax.swing.JButton btnreturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JTextField txtbookname;
    private javax.swing.JTextField txtduedate;
    private javax.swing.JTextField txtfine;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtissuedate;
    private javax.swing.JTextField txtreturndate1;
    private javax.swing.JTextField txtstudentid;
    private javax.swing.JTextField txtstudentname;
    // End of variables declaration//GEN-END:variables
}
