/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ankita
 */
public class StudentPage extends javax.swing.JFrame {

    /**
     * Creates new form StudentPage
     */
    public StudentPage() {
        initComponents();
    }
    public void getStudentDetails(){
       //int bookId = Integer.parseInt(txtbookid1.getText());
        try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");
                String sql="select * from add_student where id ='"+txtid.getText()+"'";
                 PreparedStatement pst= con.prepareStatement(sql);
                 ResultSet rs=pst.executeQuery();
                 int flag=0;
                 if(rs.next())
                  {
                     flag=1;
                     txtid.setText(rs.getString("id"));
                     txtname.setText(rs.getString("name"));
                     cmbbranch.setSelectedItem(rs.getString("branch"));
                     cmbsection.setSelectedItem(rs.getString("section"));
                 }
//                 else{
//                     txtstudenterror.setText("Invalid Student Id..!!");
//                 }
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, ""+e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnlogout = new javax.swing.JButton();
        lblid = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblbranch = new javax.swing.JLabel();
        lblsection = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        cmbbranch = new javax.swing.JComboBox<>();
        cmbsection = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnview = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlogout.setBackground(new java.awt.Color(153, 204, 255));
        btnlogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlogout.setText("Log Out");
        btnlogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlogout.setPreferredSize(new java.awt.Dimension(121, 27));
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 100, 30));

        lblid.setBackground(new java.awt.Color(255, 255, 204));
        lblid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblid.setText("Student Id");
        jPanel1.add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 40));

        lblname.setBackground(new java.awt.Color(255, 255, 204));
        lblname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblname.setText("Student Name");
        jPanel1.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, 40));

        lblbranch.setBackground(new java.awt.Color(255, 255, 204));
        lblbranch.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblbranch.setText("Student Branch");
        jPanel1.add(lblbranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 130, 40));

        lblsection.setBackground(new java.awt.Color(255, 255, 204));
        lblsection.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblsection.setText("Student Section");
        jPanel1.add(lblsection, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 130, 40));

        txtid.setBackground(new java.awt.Color(255, 255, 204));
        txtid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtidFocusLost(evt);
            }
        });
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 100, 40));

        txtname.setBackground(new java.awt.Color(255, 255, 204));
        txtname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
        });
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 240, 40));

        cmbbranch.setBackground(new java.awt.Color(255, 255, 153));
        cmbbranch.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmbbranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "Electrical Engineering", "Computer Science", "IT Engineering", "Mechanical Engineering", " " }));
        jPanel1.add(cmbbranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 240, 40));

        cmbsection.setBackground(new java.awt.Color(255, 255, 153));
        cmbsection.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmbsection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "Section A", "Section B", "Section C", "Section D", " " }));
        cmbsection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbsectionActionPerformed(evt);
            }
        });
        jPanel1.add(cmbsection, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 240, 40));

        table1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 450, 130));

        jLabel1.setFont(new java.awt.Font("HP Simplified Hans", 1, 24)); // NOI18N
        jLabel1.setText("STUDENT INFORMATION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        btnview.setBackground(new java.awt.Color(204, 204, 204));
        btnview.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnview.setText("View Books Avaliblity");
        btnview.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.black));
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });
        jPanel1.add(btnview, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 160, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 260, 5));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");
            String sql="select * from add_student where name LIKE '"+txtname.getText()+"%'";
            PreparedStatement pst= con.prepareStatement(sql);
            ResultSet rs= pst.executeQuery();
            int flag=0;
            while(rs.next())
            {
                flag=1;
                String Id= rs.getString("id");
                String Branch=rs.getString("branch");
                String Section=rs.getString("section");
                String Pass=rs.getString("password");

                cmbbranch.setSelectedItem(Branch);
                cmbsection.setSelectedItem(Section);
                txtid.setText(Id);
                //txtpass.setText(Pass);
            }
            if(flag==0)
            JOptionPane.showMessageDialog(null, "Record Not Found");
            con.close(); rs.close(); pst.close();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ""+ex.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameKeyPressed

    private void cmbsectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbsectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbsectionActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");
            String sql="select * from add_book1"; 
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            table1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ""+ex.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewActionPerformed

    private void txtidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidFocusLost
        if(!txtid.getText().equals("")){
        getStudentDetails();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidFocusLost

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        setVisible(false);
        new StartProject().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnview;
    private javax.swing.JComboBox<String> cmbbranch;
    private javax.swing.JComboBox<String> cmbsection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblbranch;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblsection;
    private javax.swing.JTable table1;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
